apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  # Add your campusid below
  namespace: nshrangare1-pipeline
spec:
  storageClassName: nshrangare1-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
